"""
Document text extractor — converts raw source files to plain text for chunking.

Supported formats
-----------------
.md   Native UTF-8 read — no transformation needed.
.pdf  PyMuPDF native text-layer extraction (born-digital PDFs).
      Scanned PDFs without a text layer return near-empty text;
      OCR (easyocr) and Vision (Qwen2.5-VL) are planned in ADR-013.

Unsupported formats (DOCX, XLSX, images, etc.) raise ``NotImplementedError``
so the corpus loader can log a warning and skip the file gracefully.

Design notes
------------
* PyMuPDF (fitz) is imported lazily inside ``_extract_pdf`` so that
  the rest of the ingestion pipeline can be imported and tested without
  the library being installed — useful for Markdown-only test fixtures.
* ``extract_text`` is the single public entry point; format detection
  is done by file extension (lower-cased) rather than MIME sniffing
  because all corpus files have canonical extensions.
"""

from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger(__name__)

# Formats understood by this module.  Checked by corpus_loader to skip
# unsupported files before calling extract_text().
SUPPORTED_SUFFIXES: frozenset[str] = frozenset({".md", ".pdf"})


def extract_text(path: Path) -> str:
    """Return the plain-text content of *path*.

    Args:
        path: Path to the source file (must exist).

    Returns:
        Extracted text as a UTF-8 string.  May be empty for scanned PDFs
        without a selectable text layer.

    Raises:
        FileNotFoundError: if *path* does not exist.
        NotImplementedError: if the file extension is not in
            ``SUPPORTED_SUFFIXES``.  See ADR-013 for the multimodal roadmap.
    """
    if not path.exists():
        raise FileNotFoundError(path)

    suffix = path.suffix.lower()

    if suffix == ".md":
        return path.read_text(encoding="utf-8")

    if suffix == ".pdf":
        return _extract_pdf(path)

    raise NotImplementedError(
        f"Unsupported document format: '{suffix}'. "
        "Supported: .md, .pdf. "
        "See ADR-013 for DOCX / XLSX / OCR / Vision roadmap."
    )


def _extract_pdf(path: Path) -> str:
    """Extract the native text layer from *path* using PyMuPDF.

    Processes each page and joins non-empty pages with a double newline
    so that chunk boundaries align with page breaks.

    Note: this is a text-layer extraction, not OCR.  Born-digital PDFs
    (generated by Word, LaTeX, etc.) work well.  Scanned PDFs will
    return empty or near-empty strings — OCR support is in ADR-013.
    """
    import fitz  # PyMuPDF — lazy import to keep test imports clean

    doc = fitz.open(str(path))
    try:
        pages: list[str] = []
        for page_num, page in enumerate(doc, start=1):
            text = page.get_text("text")
            if text.strip():
                pages.append(text)
            else:
                logger.debug(
                    "[document_processor] page %d of '%s' has no selectable text "
                    "(scanned page? OCR not yet implemented — see ADR-013)",
                    page_num, path.name,
                )
        return "\n\n".join(pages)
    finally:
        doc.close()
